version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6543:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default

  web:
    build: .
    image: cats_backend_web
    command: python manage.py runserver 0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

volumes:
  db_data:

networks:
  default:
